In [38]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import sklearn.metrics as sklm
from sklearn import preprocessing
import math
import sklearn.model_selection as ms
import numpy as np
import numpy.random as nr
%matplotlib inline

In [39]:
radiations_predict=pd.read_csv('/home/himanshi/Downloads/Dataset_Client_Live.csv')
radiations_predict.columns

Index(['UNIXTime', 'Data', 'Time', 'Radiation', 'Temperature', 'Pressure',
       'Humidity', 'WindDirection(Degrees)', 'Speed', 'TimeSunRise',
       'TimeSunSet'],
      dtype='object')

In [56]:
radiations_predict.shape
radiations_predict.dtypes

UNIXTime                    int64
Data                       object
Time                       object
Radiation                 float64
Temperature                 int64
Pressure                  float64
Humidity                    int64
WindDirection(Degrees)    float64
Speed                     float64
TimeSunRise                object
TimeSunSet                 object
dtype: object

In [46]:
radiations_predict

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,TimeSunRise,TimeSunSet
0,1475229326,9/29/2016 12:00:00 AM,23:55:26,1.21,48,30.46,59,177.39,5.62,06:13:00,18:13:00
1,1475229023,9/29/2016 12:00:00 AM,23:50:23,1.21,48,30.46,58,176.78,3.37,06:13:00,18:13:00
2,1475228726,9/29/2016 12:00:00 AM,23:45:26,1.23,48,30.46,57,158.75,3.37,06:13:00,18:13:00
3,1475228421,9/29/2016 12:00:00 AM,23:40:21,1.21,48,30.46,60,137.71,3.37,06:13:00,18:13:00
4,1475228124,9/29/2016 12:00:00 AM,23:35:24,1.17,48,30.46,62,104.95,5.62,06:13:00,18:13:00
5,1475227824,9/29/2016 12:00:00 AM,23:30:24,1.21,48,30.46,64,120.20,5.62,06:13:00,18:13:00
6,1475227519,9/29/2016 12:00:00 AM,23:25:19,1.20,49,30.46,72,112.45,6.75,06:13:00,18:13:00
7,1475227222,9/29/2016 12:00:00 AM,23:20:22,1.24,49,30.46,71,122.97,5.62,06:13:00,18:13:00
8,1475226922,9/29/2016 12:00:00 AM,23:15:22,1.23,49,30.46,80,101.18,4.50,06:13:00,18:13:00
9,1475226622,9/29/2016 12:00:00 AM,23:10:22,1.21,49,30.46,85,141.87,4.50,06:13:00,18:13:00
10,1475226323,9/29/2016 12:00:00 AM,23:05:23,1.23,49,30.47,93,120.55,2.25,06:13:00,18:13:00
11,1475226025,9/29/2016 12:00:00 AM,23:00:25,1.21,49,30.47,98,144.19,3.37,06:13:00,18:13:00
12,1475225720,9/29/2016 12:00:00 AM,22:55:20,1.22,49,30.47,99,139.80,6.75,06:13:00,18:13:00
13,1475225419,9/29/2016 12:00:00 AM,22:50:19,1.21,50,30.47,99,140.92,2.25,06:13:00,18:13:00
14,1475225131,9/29/2016 12:00:00 AM,22:45:31,1.23,50,30.47,99,147.61,5.62,06:13:00,18:13:00
15,1475224823,9/29/2016 12:00:00 AM,22:40:23,1.22,50,30.47,99,113.78,4.50,06:13:00,18:13:00
16,1475224519,9/29/2016 12:00:00 AM,22:35:19,1.21,50,30.47,99,123.03,10.12,06:13:00,18:13:00
17,1475224222,9/29/2016 12:00:00 AM,22:30:22,1.22,50,30.47,99,173.73,6.75,06:13:00,18:13:00
18,1475223919,9/29/2016 12:00:00 AM,22:25:19,1.22,50,30.47,98,91.43,6.75,06:13:00,18:13:00
19,1475223622,9/29/2016 12:00:00 AM,22:20:22,1.20,50,30.47,98,109.74,6.75,06:13:00,18:13:00
20,1475223322,9/29/2016 12:00:00 AM,22:15:22,1.20,50,30.47,98,143.53,2.25,06:13:00,18:13:00
21,1475223021,9/29/2016 12:00:00 AM,22:10:21,1.20,50,30.47,97,146.76,5.62,06:13:00,18:13:00
22,1475222720,9/29/2016 12:00:00 AM,22:05:20,1.21,50,30.47,97,158.35,4.50,06:13:00,18:13:00
23,1475222426,9/29/2016 12:00:00 AM,22:00:26,1.22,50,30.47,97,166.05,5.62,06:13:00,18:13:00
24,1475222120,9/29/2016 12:00:00 AM,21:55:20,1.22,50,30.47,96,151.82,5.62,06:13:00,18:13:00
25,1475221832,9/29/2016 12:00:00 AM,21:50:32,1.22,50,30.47,96,152.52,6.75,06:13:00,18:13:00
26,1475221528,9/29/2016 12:00:00 AM,21:45:28,1.24,50,30.47,95,127.82,7.87,06:13:00,18:13:00
27,1475221220,9/29/2016 12:00:00 AM,21:40:20,1.23,50,30.47,95,157.58,6.75,06:13:00,18:13:00
28,1475220921,9/29/2016 12:00:00 AM,21:35:21,1.23,50,30.47,95,172.96,7.87,06:13:00,18:13:00
29,1475220621,9/29/2016 12:00:00 AM,21:30:21,1.23,50,30.47,95,143.82,6.75,06:13:00,18:13:00
...,...,...,...,...,...,...,...,...,...,...,...
32656,1480595104,12/1/2016 12:00:00 AM,02:25:04,1.17,42,30.42,92,161.05,7.87,06:41:00,17:42:00
32657,1480594804,12/1/2016 12:00:00 AM,02:20:04,1.20,42,30.42,92,108.37,5.62,06:41:00,17:42:00
32658,1480594502,12/1/2016 12:00:00 AM,02:15:02,1.18,43,30.42,91,167.47,6.75,06:41:00,17:42:00
32659,1480594201,12/1/2016 12:00:00 AM,02:10:01,1.18,43,30.42,92,164.76,4.50,06:41:00,17:42:00
32660,1480593902,12/1/2016 12:00:00 AM,02:05:02,1.19,43,30.42,95,147.71,7.87,06:41:00,17:42:00
32661,1480593602,12/1/2016 12:00:00 AM,02:00:02,1.21,43,30.42,98,190.16,12.37,06:41:00,17:42:00
32662,1480593302,12/1/2016 12:00:00 AM,01:55:02,1.20,43,30.41,100,155.66,12.37,06:41:00,17:42:00
32663,1480593003,12/1/2016 12:00:00 AM,01:50:03,1.20,43,30.42,100,180.84,10.12,06:41:00,17:42:00
32664,1480592701,12/1/2016 12:00:00 AM,01:45:01,1.19,43,30.41,101,128.70,12.37,06:41:00,17:42:00
32665,1480592402,12/1/2016 12:00:00 AM,01:40:02,1.19,43,30.42,101,158.56,13.50,06:41:00,17:42:00
32666,1480592102,12/1/2016 12:00:00 AM,01:35:02,1.21,44,30.42,101,162.93,9.00,06:41:00,17:42:00
32667,1480591801,12/1/2016 12:00:00 AM,01:30:01,1.21,44,30.42,101,154.37,4.50,06:41:00,17:42:00
32668,1480591503,12/1/2016 12:00:00 AM,01:25:03,1.20,44,30.42,101,149.51,9.00,06:41:00,17:42:00
32669,1480591202,12/1/2016 12:00:00 AM,01:20:02,1.21,44,30.42,101,117.07,14.62,06:41:00,17:42:00
32670,1480590904,12/1/2016 12:00:00 AM,01:15:04,1.21,44,30.42,102,117.49,5.62,06:41:00,17:42:00
32671,1480590602,12/1/2016 12:00:00 AM,01:10:02,1.21,44,30.42,102,102.57,6.75,06:41:00,17:42:00
32672,1480590303,12/1/2016 12:00:00 AM,01:05:03,1.20,44,30.42,102,131.49,5.62,06:41:00,17:42:00
32673,1480590001,12/1/2016 12:00:00 AM,01:00:01,1.21,44,30.42,102,112.72,11.25,06:41:00,17:42:00
32674,1480589701,12/1/2016 12:00:00 AM,00:55:01,1.21,43,30.42,101,152.17,9.00,06:41:00,17:42:00
32675,1480589406,12/1/2016 12:00:00 AM,00:50:06,1.22,43,30.42,101,163.94,10.12,06:41:00,17:42:00
32676,1480589102,12/1/2016 12:00:00 AM,00:45:02,1.20,43,30.42,101,150.62,6.75,06:41:00,17:42:00
32677,1480588802,12/1/2016 12:00:00 AM,00:40:02,1.19,43,30.42,101,178.46,5.62,06:41:00,17:42:00
32678,1480588503,12/1/2016 12:00:00 AM,00:35:03,1.19,44,30.42,101,148.63,3.37,06:41:00,17:42:00
32679,1480588205,12/1/2016 12:00:00 AM,00:30:05,1.21,44,30.42,101,101.27,10.12,06:41:00,17:42:00
32680,1480587902,12/1/2016 12:00:00 AM,00:25:02,1.18,44,30.42,102,121.02,4.50,06:41:00,17:42:00
32681,1480587604,12/1/2016 12:00:00 AM,00:20:04,1.22,44,30.43,102,145.42,6.75,06:41:00,17:42:00
32682,1480587301,12/1/2016 12:00:00 AM,00:15:01,1.17,44,30.42,102,117.78,6.75,06:41:00,17:42:00
32683,1480587001,12/1/2016 12:00:00 AM,00:10:01,1.20,44,30.42,102,145.19,9.00,06:41:00,17:42:00
32684,1480586702,12/1/2016 12:00:00 AM,00:05:02,1.23,44,30.42,101,164.19,7.87,06:41:00,17:42:00
32685,1480586402,12/1/2016 12:00:00 AM,00:00:02,1.20,44,30.43,101,83.59,3.37,06:41:00,17:42:00

In [51]:
#cols = ['price', 'bore', 'stroke',
#         'horsepower', 'peak_rpm']
#for column in cols:
#    auto_prices.loc[auto_prices[column] == '?', column] = np.nan
#auto_prices.dropna(axis = 0, inplace = True)
#auto_prices.shape

NameError: name 'Radiation' is not defined

In [41]:
Features = np.array(radiations_predict[['UNIXTime','Temperature','Pressure', 'Humidity', 'Speed']])
Features[:2,:]

array([[1.47522933e+09, 4.80000000e+01, 3.04600000e+01, 5.90000000e+01,
        5.62000000e+00],
       [1.47522902e+09, 4.80000000e+01, 3.04600000e+01, 5.80000000e+01,
        3.37000000e+00]])

In [42]:
nr.seed(9988)
labels = np.array(radiations_predict['Radiation'])
indx = range(Features.shape[0])
print(indx)
indx = ms.train_test_split(indx, test_size = 40)
x_train = Features[indx[0],:]
y_train = np.ravel(labels[indx[0]])
x_test = Features[indx[1],:]
y_test = np.ravel(labels[indx[1]])
print(y_train)

range(0, 32686)
[855.12   1.19 119.48 ...   1.26 115.67 823.07]

In [43]:
lin_mod = linear_model.LinearRegression(fit_intercept = False)
lin_mod.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)

In [52]:
scaler = preprocessing.StandardScaler().fit(x_train[:,:])
x_train[:,:] = scaler.transform(x_train[:,:])
x_test[:,:] = scaler.transform(x_test[:,:])
print(x_train.shape)
x_train[:5,:]

(32646, 5)

array([[-1.09766187,  1.59581159,  1.22779679,  0.61510167,  0.46579035],
       [-0.45028761,  0.30586615,  1.41073156, -1.38543416,  0.46579035],
       [ 1.55493651, -0.66159293, -0.23568135,  0.76898905,  0.46579035],
       [-0.34706866,  0.95083887,  0.31312295, -0.23127887, -0.8233322 ],
       [-1.190608  , -0.82283611, -0.78448566,  0.76898905,  0.78950334]])

In [53]:
def print_metrics(y_true, y_predicted, n_parameters):
    ## First compute R^2 and the adjusted R^2
    r2 = sklm.r2_score(y_true, y_predicted)
    r2_adj = r2 - (n_parameters - 1)/(y_true.shape[0] - n_parameters) * (1 - r2)
    
    ## Print the usual metrics and the R^2 values
    print('Mean Square Error      = ' + str(sklm.mean_squared_error(y_true, y_predicted)))
    print('Root Mean Square Error = ' + str(math.sqrt(sklm.mean_squared_error(y_true, y_predicted))))
    print('Mean Absolute Error    = ' + str(sklm.mean_absolute_error(y_true, y_predicted)))
    print('Median Absolute Error  = ' + str(sklm.median_absolute_error(y_true, y_predicted)))
    print('R^2                    = ' + str(r2))
    print('Adjusted R^2           = ' + str(r2_adj))
   
y_score = lin_mod.predict(x_test) 
print(y_score)
print_metrics(y_test, y_score, 28)

[ 1.95205695e+03 -1.89296743e+02  3.08017150e+02 -5.04358593e+02
 -2.39724408e+02 -8.70278016e+02  1.12633129e+02  5.59769080e+01
  5.92679518e-01  1.70801276e+02 -2.62072015e+02 -3.88499426e+02
  1.69609037e+03 -8.08739635e+02  6.27461215e+01 -7.83560487e+02
  2.79692289e+03 -4.61721617e+02 -1.93157203e+02  8.84757240e+02
  3.10844153e+02 -1.99947270e+02 -6.15393790e+02  4.20839545e+02
  4.66477788e+02 -3.01383673e+02  5.47320519e+02 -5.09189636e+02
 -3.96346319e+02 -6.94474647e+02 -2.81425831e+02  1.74803573e+03
  1.25710061e+02  5.69090299e+01 -1.34778704e+03 -1.24814381e+02
 -7.95194698e+02 -5.18986406e+02  3.35165777e+02  4.44208686e+02]
Mean Square Error      = 824714.8961494479
Root Mean Square Error = 908.138148163289
Mean Absolute Error    = 683.5303953416242
Median Absolute Error  = 515.3230212747189
R^2                    = -5.638262743659512
Adjusted R^2           = -20.574353916893415